SAGERPNEW2018/Controllers/ActivityLogController.cs
using HRandPayrollSystemModel.DBModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Filters;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{

    [NoCache]
    [OutputCache(Location = System.Web.UI.OutputCacheLocation.None, NoStore = true)]
    public class ActivityLogController : Controller
    {
        // GET: ActivityLog
        [UserRightFilters]
        public ActionResult Index()
        {
            ProjectActivityLog a = new ProjectActivityLog();
            a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
            a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
            a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
            a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);

            
            return View(a);
        }
        [UserRightFilters]
        public ActionResult create(ProjectActivityLog a)
        {
            try
            {
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);
              
               

                return View(a);
            }
            catch (Exception ex)
            {

                return View(a);
            }

        }

        public ActionResult Save(ProjectActivityLog model, FormCollection collection)
        {
            long check=0;

            if (model.Idlog > 0)
            {
                model.Modifeddate = DateTime.Now;
                model.Modifedyid = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid; 
                model.Modifiedip = Request.UserHostAddress;
                check = model.update(model);

            }
            else
            {
                model.CreatedOn = DateTime.Now;
                model.CreatedIP = Request.UserHostAddress;
                model.CreatedBy = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid;
                check = model.addata(model);

            }

          

            if (check > 0)
            {
                ViewData["Message"] = "Success";
                return RedirectToAction("Index");

            }
            return RedirectToAction("create", model);
        }

        [UserRightFilters]

        public ActionResult Edit(string id)
        {
            try
            {
                string[] IDo = id.Split('|');

                ProjectActivityLog a = new ProjectActivityLog();
                var obj = a.getalldataedit(Convert.ToInt32(IDo[0]));
                if (IDo[1] == "0")
                {
                    a.IsView = true;
                }
                obj.IsView = a.IsView;
                obj.Idlog = Convert.ToInt32(IDo[0]);
                return View("create", obj);

            }
            catch (Exception ex)
            {
                return View("create");
            }

        }


        public ActionResult viewlist()
        {
            ProjectActivityLog a = new ProjectActivityLog();
            

            return View(a);
        }


    }
}

SAGERPNEW2018/Views/ActivityLog/Index.cshtml
@model HRandPayrollSystemModel.DBModel.ProjectActivityLog

@{
    ViewBag.Title = "Support and Services Monitoring";
}


<div id="modals"></div>

<header class="page-header">
    <h2>@ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
      
        
        <ol class="breadcrumbs">


            <li>
                <a href="~/home/index">
                    <i class="fa fa-home" style="color:chartreuse;"></i>

                </a>
            </li>
            <li>
                <a style="color:chartreuse" href="/Eminute//create">
                    Create E-Minute      @*<i class="fa fa-home"></i>*@
                </a>
            </li>
            <li>
                <a style="color:chartreuse" href="/Eminute//AllMinutesReport">
                    Report      @*<i class="fa fa-home"></i>*@
                </a>
            </li>
            <li>
                <a href="#" onclick="showInstruction()" style="color: chartreuse;">
                    <i class="fa fa-info-circle"></i>      E-Minute Guideline
                </a>
            </li>



        </ol>
        
        
   
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All @ViewBag.Title Data</h2>
    </header>
    <div class="panel-body">
        
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>

        <table class="table table-bordered  mb-none table-hover" id="UserTable">
            <thead>
                <tr class="primary">

                    <th>Sr#</th>
                    <th>Service Name</th>
                    <th>Location </th>
                    <th>Reported By </th>
                    <th>Resolved By </th>
                    <th>Elapsed Time </th>

                    <th>Status</th>
                    @*<th>Reported Date</th>
        <th>Resolved Date</th>*@

                    <th width="30px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @{int a=1; }
                @foreach (var item in Model.getalldata())
                {
                <tr>
                    <td>@a </td>
                    <td> @item.ServiceDetail.ToUpper()
                    <td> @item.ProjectName.ToUpper() </td>
                    <td> @item.reslovedemployee    @item.CreatedOn.Value.ToString("dd/MM/yyyy") -  @string.Format("{0:hh:mm:ss tt}", item.CreatedOn)  </td>
                    <td> @item.EmployeeName   @string.Format("{0:dd/MM/yyyy}", item.Modifeddate)  -  @string.Format("{0:hh:mm:ss tt}", item.Modifeddate)   </td>

                    <td align="center">  <strong>@item.hourss hr</strong>   </td>

                    @if (@item.ServiceActive.ToUpper() == "ACTIVE")
                    {
                        <td align="center">  <button type="button" class="btn btn-success btn-xs"> ACTIVE</button> </td>

                    }
                    else
                    {
                        <td align="center">  <button type="button" class="btn btn-danger  btn-xs"> INACTIVE</button> </td>
                    }


                    @*<td>  @item.CreatedOn.Value.ToString("dd/MM/yyyy") -  @string.Format("{0:hh:mm:ss tt}", item.CreatedOn) </td>
        <td>  @string.Format("{0:dd/MM/yyyy}", item.Modifeddate)  -  @string.Format("{0:hh:mm:ss tt}", item.Modifeddate)    </td>*@


                    @*<td> @item.Modifeddate </td>
        <td> @item.Modifedyid </td>*@


                    <td>
                        @if (Convert.ToBoolean(Model.Isedit))
                        {

                            <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.Idlog)">
                                <i class="fa fa-pencil"></i>

                            </a>
                        }

                        <a href="#" class="on-default edit-row" title="View" onclick="view(@item.Idlog)">
                            <i class="fa fa-table"></i>

                        </a>
                    </td>

                </tr>
                    a++;
                }
            </tbody>

        </table>
    </div>

</section>


<script>

    $(document).ready(function () {
        //$('#btnTriggerEdit').click();
        $("#modals").load('/CustomClasses/IndexModaling.html')


            $("#UserTable").dataTable(
               {
                    "aoColumns": [{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true },{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true },{ "bSearchable": true },
                       { "bSearchable": false }],
                   "bSort": true,

                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',
                           title: 'Support and Services Monitoring',
                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: 'Support and Services Monitoring',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: 'Support and Services Monitoring',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: 'Support and Services Monitoring',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: 'Support and Services Monitoring',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
            var a = '@TempData["Dependancy"]'
            if (a != "") {
                $("#basicDendent").modal('show');
            }
        })

        function add() {
            window.location.href = "/ActivityLog/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/ActivityLog/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/ActivityLog/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/ActivityLog/Edit/" + id + "|0"

        }

</script>

SAGERPNEW2018/Views/ActivityLog/create.cshtml
@model HRandPayrollSystemModel.DBModel.ProjectActivityLog

@{
    ViewBag.Title = "Support and Services Monitoring ";
}


@using (@Html.BeginForm("Save", "ActivityLog", FormMethod.Post, new { @id = "myform", enctype = "multipart/form-data" }))
{
    if (Model.Idlog > 0)
    {
        if (Model.IsView)
        {
            ViewBag.Title = "Support and Services Monitoring View";
        }
        else
        {
            ViewBag.Title = "Support and Services Monitoring Edit";
        }

    }
    else
    {

        ViewBag.Title = " Support and Services Monitoring Create";

    }

    <header class="page-header">
        <h2>@ViewBag.Title</h2>
       

        <div class="right-wrapper pull-right">

            <ol class="breadcrumbs">


                <li>
                    <a href="~/home/index">
                        <i class="fa fa-home" style="color:chartreuse;"></i>

                    </a>
                </li>
                <li>
                    <a style="color:chartreuse" href="/Eminute//create">
                        Create E-Minute      @*<i class="fa fa-home"></i>*@
                    </a>
                </li>
                <li>
                    <a style="color:chartreuse" href="/Eminute//AllMinutesReport">
                        Report      @*<i class="fa fa-home"></i>*@
                    </a>
                </li>
                <li>
                    <a href="#" onclick="showInstruction()" style="color: chartreuse;">
                        <i class="fa fa-info-circle"></i>      E-Minute Guideline
                    </a>
                </li>



            </ol>

            @*<ol class="breadcrumbs">
                <li>
                    <a href="~/home/index">

                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Setup</span></li>
                <li><span>Service Log Info</span></li>
            </ol>*@

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->

   
        <br />
        <br />
        <br />

        <div class="row">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.Idlog)

                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title"> @ViewBag.Title</h2>
                        <p class="panel-subtitle">
                            Form control for input @ViewBag.Title .
                        </p>
                    </header>
                    <div class="panel-body">

                     <br />
                        <div class="form-group">






                            <div class="row">



                                <label class="col-sm-1 control-label"><strong> Project:</strong> </label>
                                <div class="col-md-3 ">

                                    @Html.DropDownListFor(model => model.ProjectIDs, new HRandPayrollSystemModel.DBModel.tblEmployee().loadProject(), new { @class = "form-control selectpicker ", @required = "required", })




                                    @*<select class="selectpicker form-control" id="ProjectIDs" name="ProjectIDs">
                                        @{
                                            var getdropdown = new HRandPayrollSystemModel.DBModel.tblEmployee().loadProject();
                                            foreach (var item in getdropdown)
                                            {
                                                <option value="@item.Value"> @item.Text </option>
                                            }

                                        }
                                    </select>*@

                                </div>



                                <label class="col-sm-1 control-label"><strong>Service Type:</strong> </label>
                                <div class="col-md-3 ">


                                    @Html.DropDownListFor(model => model.ServiceTypeID, Model.LoadSericeTypes(), new { @class = "form-control selectpicker ", @required = "required", })




                                    @*<select class="selectpicker form-control" id="ServiceTypeID" name="ServiceTypeID">
                                        @{
                                            var oi = new HRandPayrollSystemModel.DBModel.ProjectActivityLog().LoadSericeTypes();
                                            foreach (var item in oi)
                                            {
                                                <option value="@item.Value"> @item.Text </option>
                                            }

                                        }
                                    </select>*@

                                </div>




                            </div>
                            <br />


                            <div class="row">
                                @if (Model.Idlog > 0)
                                {
                                <label class="col-sm-1 control-label"><strong>Resolved Employee:</strong> </label>


                                <div class="col-md-3">


                                    @Html.DropDownListFor(model => model.Employeeid, Model.loadEmployee(), new { @class = "form-control selectpicker ", @required = "required", })




                                    @*<select class="selectpicker form-control" id="Employeeid" name="Employeeid">
                                        @{
                                            var Employee = new HRandPayrollSystemModel.DBModel.GLUser().loadAllActiveEmployee();
                                            foreach (var item in Employee)
                                            {
                                                <option value="@item.Value"> @item.Text </option>
                                            }

                                        }
                                    </select>*@


                                </div>
                                            }

                                <label class="col-sm-1 control-label"><strong>Status:</strong> </label>


                                <div class="col-md-3">

                                    @Html.DropDownListFor(model => model.ServiceActive, Model.loadAllActive(), new { @class = "form-control selectpicker ", @required = "required", })

                                    
                                    
                                    @*<select class="form-control selectpicker" data-style="btn-warning" id="ServiceActive" name="ServiceActive" style="font-size: large;padding: 1px;">




                                        <option value="Active" name="">Active</option>
                                        <option value="Inactive" name="">Inactive</option>



                                    </select>*@



                                </div>

                            </div>
                            <br />
                            <br />



                        </div>


                        </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="button" id="cancelll" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}





<script>

    $(document).ready(function () {
        var DateofP = '01' + '/' + new Date().getMonth() + '/' + new Date().getFullYear();

        $('#FromDate').datepicker('setDate', DateofP);
        $("#ToDate").datepicker({
            format: "dd-M-yyyy",
            autoclose: true,
            todayBtn: true,


        });
        $('#FromDate').datepicker('setDate', new Date());
        $('#ToDate').datepicker('setDate', new Date());


    })






    function postform() {
        debugger;
        var ReturnValue = true



        var ReturnValue = true

        if ($("#ProjectIDs").val() == "0") {
            $('#ProjectIDs').selectpicker('setStyle', 'btn-danger');
            $('#ProjectIDs').selectpicker('refresh');

            ReturnValue = false;
        }


        if ($("#ServiceTypeID").val() == "0") {
            $('#ServiceTypeID').selectpicker('setStyle', 'btn-danger');
            $('#ServiceTypeID').selectpicker('refresh');

            ReturnValue = false;
        }



        $("#myform").validate();





        if (ReturnValue) {
            $("#myform").submit();

        }

    }
    $(document).ready(function () {
       // $('#Myform :input').select()




        $('.selectpicker').selectpicker('selectAll');

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }
      

    });

    function loadDepartments() {

        var Department = $('#DepartmentID');
        Department.empty();
        var Data = { id: $('#ProjectID').val() }
        $.ajax({
            async: false,
            url: "/Designation/loadDepartments",
            data: Data,
            success: function (data) {


                var Department = $('#DepartmentID');
                Department.empty();

               // alert(data);
                $.each(data,
                    function (index, item) {
                        var datafil = new Option(item.Text, item.Value);
                        Department.append(datafil);
                    });


                Department.selectpicker({
                    liveSearch: true,
                    size: 10,

                    // width: 'auto',
                    container: "body"
                });

                Department.selectpicker('refresh');


            },
            error: function () {
                ReturnValue = false;
                //alert("Error")
            }
        })

    }



</script>