SAGERPNEW2018/Controllers/CityController.cs
using HRandPayrollSystemModel.DBModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class CityController : Controller
    {
        // GET: City
    
        [UserRightFilters]
        public ActionResult Index()
        {
            try
            {
                CityInformtion a = new CityInformtion();
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);
                return View(a);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [UserRightFilters]
        public ActionResult create(CityInformtion a)
        {
            try
            {
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);


                return View(a);
            }
            catch (Exception ex)
            {

                return View(a);
            }

        }
        [UserRightFilters]
        public ActionResult delete(int id)
        {
            try
            {
                CityInformtion a = new CityInformtion();

                bool c = a.DeleteData(id);
                if (c)
                {
                    return RedirectToAction("Index");

                }
                TempData["Dependancy"] = "This Record Using In Another Table";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }


        }
        [UserRightFilters]

        public ActionResult Edit(string id)
        {
            try
            {
                string[] IDo = id.Split('|');

                CityInformtion a = new CityInformtion();
                var obj = a.getAlldataByID(Convert.ToInt32(IDo[0]));
                if (IDo[1] == "0")
                {
                    a.IsView = true;
                }
                obj.IsView = a.IsView;
                obj.CityID = Convert.ToInt32(IDo[0]);
                return View("create", obj);

            }
            catch (Exception ex)
            {
                return View("create");
            }

        }

        [UserRightFilters]

        public ActionResult Save(CityInformtion model)
        {
            try
            {
                int check;

                if (model.CityID > 0)
                {
                    model.ModifiedDate = DateTime.Now;
                    model.ModifiedID = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid;
                    model.ModifiedIP = new SAGERPNEW2018.Models.SystemLogin().GetUser().system;
                    check = check = model.UpdateData(model);
                  
                }
                else
                {
                    model.EntryDate = DateTime.Now;
                    model.EntryID = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid ;
                    model.EntryIP = new SAGERPNEW2018.Models.SystemLogin().GetUser().system;
                    check = model.addata(model);
                    
                }

                if (check > 0)
                {
                    TempData["ActionMessage"] = true;
                    return RedirectToAction("Index");

                }
                TempData["ActionMessage"] = false;
                return RedirectToAction("create", model);



            }
            catch (Exception ex)
            {
                TempData["ActionMessage"] = false;

                return View("create");
            
            }
        }

        public ActionResult Duplicate(string Name, string ID)
        {
            try
            {
                string json = "";
                var list = new CityInformtion().checkDuplicate(Convert.ToInt32(ID), Name);
                if (list.Count() > 0)
                {
                    json = " Duplicate Record Found ";
                }
                return Json(JsonConvert.SerializeObject(json), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {


                return Json(JsonConvert.SerializeObject("Error"), JsonRequestBehavior.AllowGet);

            }


        }
    }
}

SAGERPNEW2018/Views/City/Index.cshtml
@model HRandPayrollSystemModel.DBModel.CityInformtion

@{
    ViewBag.Title = "City Information";
}


<div id="modals"></div>

<header class="page-header">
    <h2>@ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="~/home/index">

                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Setup</span></li>
            <li><span>@ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All @ViewBag.Title Data</h2>
    </header>
    <div class="panel-body">

        @if (TempData["ActionMessage"] != null)
        {
            if (Convert.ToBoolean(TempData["ActionMessage"]))
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success">
                            <strong>Success!</strong> Record Save Successfully .
                        </div>
                    </div>


                </div>

            }
            else
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-danger">
                            <strong>Error!</strong> Record Save Error .
                        </div>
                    </div>


                </div>
            }
        }



        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-none table-hover" id="UserTable">
            <thead>
                <tr>

                    <th> City Tite </th>
                    <th>Inactive </th>

                    <th width="100px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @foreach (var item in Model.getAllCitydata())
                {
                    <tr>

                        <td> @item.CityName </td>
                        <td> @item.inactive </td>


                        <td>
                            @if (Convert.ToBoolean(Model.Isedit))
                            {

                                <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.CityID)">
                                    <i class="fa fa-pencil"></i>

                                </a>
                            }
                            @*@if (Convert.ToBoolean(Model.Isdelete))
                                {
                                    <a href="#basic" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Delete" onclick="Del(@item.ProjectID)">
                                        <i class="glyphicon glyphicon-trash"></i>

                                    </a>
                                }*@
                            <a href="#" class="on-default edit-row" title="View" onclick="view(@item.CityID)">
                                <i class="fa fa-table"></i>

                            </a>
                            @*<button class="btn btn-success btn-xs" onclick="view(@item["Voucherid"])"><span class="glyphicon glyphicon-blackboard"></span> View</button>*@
                        </td>

                    </tr>
                }
            </tbody>

        </table>
    </div>

</section>


<script>

    $(document).ready(function () {
        //$('#btnTriggerEdit').click();
        $("#modals").load('/CustomClasses/IndexModaling.html')


            $("#UserTable").dataTable(
               {
                   "aoColumns": [{ "bSearchable": true }, { "bSearchable": true },
                       { "bSearchable": false }],
                   "bSort": true,

                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',
                                  title: '@ViewBag.Title',
                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: '@ViewBag.Title',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: '@ViewBag.Title',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: '@ViewBag.Title',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: '@ViewBag.Title',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
            var a = '@TempData["Dependancy"]'
            if (a != "") {
                $("#basicDendent").modal('show');
            }
        })

        function add() {
            window.location.href = "/City/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/City/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/City/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/City/Edit/" + id + "|0"

        }

</script>

SAGERPNEW2018/Views/City/create.cshtml
@model HRandPayrollSystemModel.DBModel.CityInformtion

@{
    ViewBag.Title = "City Information";
}



@using (@Html.BeginForm("Save", "City", FormMethod.Post, new { @id = "myform", enctype = "multipart/form-data" }))
{
    if (Model.CityID > 0)
    {
        if (Model.IsView)
        {
            ViewBag.Title = ViewBag.Title+" View";
        }
        else
        {
            ViewBag.Title = ViewBag.Title+" Edit";
        }

    }
    else
    {

        ViewBag.Title = ViewBag.Title+" Create";

    }

    <header class="page-header">
        <h2>@ViewBag.Title</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="~/home/index">

                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Setup</span></li>
                <li><span>@ViewBag.Title</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">EmployeeType Info</h2>
                        <p class="panel-subtitle">
                            Form control for input EmployeeType data .
                        </p>
                    </header>
                    <div class="panel-body">



                        @Html.HiddenFor(model => model.CityID)
                        <div class="form-group">
                            <label class="col-sm-3 control-label">City Title <span class="required">*</span></label>
                            <div class="col-sm-6 ">
                                @Html.TextBoxFor(model => model.CityName, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Title" })

                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label">InActive</label>
                            <div class="col-sm-9 ">
                                @Html.CheckBoxFor(model =>  model.inactive)
                                @*<input id="Inactive" name="Inactive" type="checkbox" value="@Model.Inactive" />*@

                            </div>
                        </div>





                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="button" id="cancelll" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}





<script>




    function postform() {
        var ReturnValue = true

      

        $("#myform").validate();



        var Data = { Name: $('#CityName').val(), ID: $("#CityID").val() }
        $.ajax({
            async: false,
            url: "/City/Duplicate",
            data: Data,
            success: function (data) {

                var c =JSON.parse(data);
                if (c!="") {
                    bootbox.alert(c)
                    ReturnValue = false;
                }
            },
            error: function () {
                ReturnValue = false;
                bootbox.alert("Error")
            }
        })


        bootbox.confirm("Are sure to save data!", function (result) {
            if (result) {
                if (ReturnValue) {
                    $("#myform").submit();

                }

            }
        });


    }
    $(document).ready(function () {
       // $('#Myform :input').select()

        $('.selectpicker').selectpicker('selectAll');

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }

    });


</script>