SAGERPNEW2018/Controllers/NavbarController.cs
using HRandPayrollSystemModel.DBModel;
using SAGERPNEW2018.Domain;
using SAGERPNEW2018.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    [OutputCache(Location = System.Web.UI.OutputCacheLocation.None, NoStore = true)]
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult NavBarView()
        {
        
             sp_GetUserRightByUser_Result nav = new sp_GetUserRightByUser_Result();
           var User = new SystemLogin().GetUser();
            var ass = new SystemLogin().checkRightUser(User.Userid).Where(x => x.Assign == true).ToList();
            return PartialView("_Navigation", new SystemLogin().checkRightUser(User.Userid).Where(x=>x.Assign==true).ToList());

        }
    }
}

SAGERPNEW2018/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="fixed js flexbox flexboxlegacy csstransforms csstransforms3d no-overflowscrolling no-mobile-device custom-scroll sidebar-left-collapsed">
<head>
    <title>@ViewBag.Title </title>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    @*<meta name="viewport" content="width=100%, initial-scale=0.1, user-scalable=no">*@
    @*<meta name="viewport" content="width=">*@
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />*@
   
    @{

//var logolink = new SAGERPNEW2018.Models.SystemLogin().Getcompany().CompanyLogo.ToString();
        <link rel="shortcut icon" href="~/AppFiles/Images/logo2.png" class="img-rounded" type="image/x-icon">
            <link rel="icon" href="~/AppFiles/Images/logo2.png" type="image/x-icon">

        @*<link rel="shortcut icon" href="~/assets/images/ERPlogo.png" type="image/x-icon">
        <link rel="icon" href="~/assets/images/ERPlogo.png" type="image/x-icon">*@
    }
   

   
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/assets/vendor/magnific-popup/magnific-popup.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
    <link rel="stylesheet" href="/assets/vendor/select2/select2.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css" />
    <link rel="stylesheet" href="/assets/vendor/dropzone/css/basic.css" />
    <link rel="stylesheet" href="/assets/vendor/dropzone/css/dropzone.css" />
    <link rel="stylesheet" href="/assets/vendor/bootstrap-markdown/css/bootstrap-markdown.min.css" />
    <link rel="stylesheet" href="/assets/vendor/summernote/summernote.css" />
    <link rel="stylesheet" href="/assets/vendor/summernote/summernote-bs3.css" />
    <link rel="stylesheet" href="/assets/vendor/codemirror/lib/codemirror.css" />
    <link rel="stylesheet" href="/assets/vendor/codemirror/theme/monokai.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="/assets/stylesheets/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="/assets/stylesheets/skins/default.css" />
    <!-- Vendor CSS -->
    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="/assets/vendor/pnotify/pnotify.custom.css" />

    <link rel="stylesheet" href="/assets/stylesheets/theme-custom.css">

   
    
    <!-- Vendor -->
    <script src="/assets/vendor/jquery/jquery.js"></script>
    <script src="/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>


    <!-- Specific Page model -->
    <script src="/assets/vendor/pnotify/pnotify.custom.js"></script>

    <!-- Theme Base, Components and Settings -->
    <!-- Examples -->
    <script src="/assets/javascripts/ui-elements/examples.modals.js"></script>
    <!-- Head Libs -->
    <script src="/assets/vendor/modernizr/modernizr.js"></script>
    <script src="/Scripts/AutoType/auto.max.min.js"></script>
    <link rel="stylesheet" href="/assets/vendor/pnotify/pnotify.custom.css" />
    @*<link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.css" />*@

    <style>
        a:hover {
            text-decoration: none;
        }


            .myBtnnew {
    display: none;
    position: fixed;
    bottom: 20px;
    right: 30px;
    z-index: 99;
    border: none;
    outline: none;
    background-color: #2ed459;
    color: white;
    cursor: pointer;
    padding: 7px;
    border-radius: 4px;
    }

    .myBtnnew:hover {
    background-color: #555;
    }
    </style>




</head>

<body  style="overflow-y:auto" >


    <button onclick="topFunction()" class="btn btn-success btn-xs myBtnnew" id="myBtn" data-toggle="tooltip"  title="Go to top"><i class="fa fa-arrow-up" aria-hidden="true"> </i>    </button>
    <section class="body"  >
        
            <div class="inner-wrapper">
               @Html.Action("NavBarView", "Navbar")
                <br />
                @*@{Html.RenderAction("Index", "Navbar", null);}*@
                <section role="main" class="content-body" style="margin-top:-80px;padding:0px">
                    @RenderBody()
                </section>
        </div>

      
</section>
    <!-- Specific Page Vendor -->
    <script src="/assets/vendor/pnotify/pnotify.custom.js"></script>

    <!-- Examples -->
    <script src="/assets/javascripts/ui-elements/examples.modals.js"></script>


    <script src="/Content/dataTables1/datatables.min.js"></script>
    <script src="/Scripts/datatable/Buttons-1.5.1/js/buttons.colVis.js"></script>


        @*@Styles.Render("~/Content/dataTables/dataTablesStyles")
        @Scripts.Render("~/Content/dataTables1")*@

    <link rel="stylesheet" href="/Content/dataTables/datatables.min.css" />
    <link rel="stylesheet" href="/Scripts/datatable/Buttons-1.5.1/css/buttons.dataTables.min.css" />

    <link rel="stylesheet" href="/Scripts/DataTables/Buttons-1.5.1/css/buttons.bootstrap4.min.css" />
    <link rel="stylesheet" href="/Scripts/DataTables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="/Scripts/DataTables/Buttons-1.5.1/css/buttons.jqueryui.min.css" />

    <link rel="stylesheet" href="/Scripts/DataTables/Buttons-1.5.1/css/buttons.bootstrap.min.css" />

    <link rel="stylesheet" href="/Scripts/DataTables/Responsive-2.2.1/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" href="/Scripts/DataTables/Buttons-1.5.1/css/buttons.semanticui.min.css" />





    <!-- Specific Page Vendor -->
    <script src="/assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
    <script src="/assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
    <script src="/assets/vendor/select2/select2.js"></script>
    <script src="/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
    <script src="/assets/vendor/jquery-maskedinput/jquery.maskedinput.js"></script>
    <script src="/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script src="/assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
    <script src="/assets/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
    <script src="/assets/vendor/fuelux/js/spinner.js"></script>
    <script src="/assets/vendor/dropzone/dropzone.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/markdown.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/to-markdown.js"></script>
    <script src="/assets/vendor/bootstrap-markdown/js/bootstrap-markdown.js"></script>
    <script src="/assets/vendor/codemirror/lib/codemirror.js"></script>
    <script src="/assets/vendor/codemirror/addon/selection/active-line.js"></script>
    <script src="/assets/vendor/codemirror/addon/edit/matchbrackets.js"></script>
    <script src="/assets/vendor/codemirror/mode/javascript/javascript.js"></script>
    <script src="/assets/vendor/codemirror/mode/xml/xml.js"></script>
    <script src="/assets/vendor/codemirror/mode/htmlmixed/htmlmixed.js"></script>
    <script src="/assets/vendor/codemirror/mode/css/css.js"></script>
    <script src="/assets/vendor/summernote/summernote.js"></script>
    <script src="/assets/vendor/bootstrap-maxlength/bootstrap-maxlength.js"></script>
    <script src="/assets/vendor/ios7-switch/ios7-switch.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="/assets/javascripts/theme.js"></script>

    <!-- Theme Custom -->
    <script src="/assets/javascripts/theme.custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="/assets/javascripts/theme.init.js"></script>

    <script src="/assets/javascripts/forms/examples.advanced.form.js"></script>

    <!-- Validation  Files -->
    <script src="/assets/vendor/jquery-validation/jquery.validate.js"></script>
    <script src="/assets/javascripts/forms/examples.validation.js"></script>
    <script src="/assets/vendor/select2/select2.js"></script>
    <link href="~/Content/bootstrap-select.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-select.min.js"></script>

    <script src="~/Scripts/bootbox.min.js"></script>



   
    <script>

        $('.number').keypress(function (event) {
            if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });

        $('.selectpicker').selectpicker({
            liveSearch: true,
            container: "body"
        });
        $('.selectpicker').selectpicker('refresh');

        $('.select').select2({
            selectOnClose: true
        });






        //Get the button
        var mybutton = document.getElementById("myBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }



    </script>
        @RenderSection("scripts", required: false)





</body>



</html>

SAGERPNEW2018/Views/Shared/_minuteGudie.cshtml
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="width:902px;margin-left:-143px;">
            <div class="modal-header " style="background:#820606;">
                <button type="button" class="close" style="opacity: 1;" data-dismiss="modal">&times;</button>

                <h4 class="modal-title" style="color:white"> E-Minute Sheet Guidelines</h4>
            </div>
            <div class="modal-body">


                <div class="list-group">
                    <a href="#" class="list-group-item active"><strong> Following steps/guidelines may be considered while using E-Minute module:</strong></a>

                    <a href="#" class="list-group-item list-group-item-success"><strong>1. Type of Minute .</strong></a>
                    <a href="#" class="list-group-item">
                        <strong>1.</strong>	For demand of any new equipment of any value (Medical, electrical, office or computer equipment) related type should be selected.

                        <br />
                        <strong>2.</strong>	For maintenance of existing equipment anything more than Rs.25,000/ “Repair Maintenance” type should be selected.
                        <br />

                        <strong>3.</strong>	For new vehicle, “MT/Vehicle” type to be selected.
                        <br />
                        <strong>4.</strong>	Stock Items: This type is only for Logistics branch for approval of new item or increase in price.

                    </a>
                    @*<a href="#" class="list-group-item"><strong>2.</strong>	For maintenance of existing equipment anything more than Rs.25,000/ “Repair Maintenance” type should be selected.</a>
                        <a href="#" class="list-group-item"><strong>3.</strong>	For new vehicle, “MT/Vehicle” type to be selected.</a>
                        <a href="#" class="list-group-item"><strong>4.</strong>	Stock Items: This type is only for Logistics branch for approval of new item or increase in price.</a>*@
                    <a href="#" class="list-group-item list-group-item-success"><strong>1.5. Non Stock Items.</strong></a>
                    <a href="#" class="list-group-item">

                        <strong>1.</strong> This is applicable for “Computer equipment” and “Repair & maintenance” type of minutes only.
                        <br />
                        <strong>2. </strong> In Repair Maintenance, sub type includes furniture fixture, civil works, medical equipment, non-medical equipment, vehicles etc.

                    </a>
                    @*<a href="#" class="list-group-item "><strong>1.</strong> This is applicable for “Computer equipment” and “Repair & maintenance” type of minutes only.</a>
                        <a href="#" class="list-group-item "><strong>2. </strong> In Repair Maintenance, sub type includes furniture fixture, civil works, medical equipment, non-medical equipment, vehicles etc.</a>*@
                    <a href="#" class="list-group-item list-group-item-success"><strong>2. Technical Person .</strong></a>
                    <a href="#" class="list-group-item">
                        <strong>1. HOD should seek input of relevant technical person for various types of minutes as below:</strong>

                        <table class="table table-bordered mb-none table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Type</th>
                                    <th>Technical Person</th>

                                </tr>

                            </thead>
                            <tbody>

                                <tr>
                                    <td>1</td>
                                    <td>Medical Equipment </td>
                                    <td>Manager Biomedical</td>
                                </tr>

                                <tr>
                                    <td>2</td>
                                    <td>Electrical/Other Equipment </td>
                                    <td>Manager Maintenance</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Office Equip./Furniture & Fixtures/Vehicle/General Items  </td>
                                    <td>Manager Admin</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>Computer Equipment /Software</td>
                                    <td>GM IT</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Civil Projects / Works</td>
                                    <td>Manager Projects</td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td>Stock Items</td>
                                    <td>Chief Consultant </td>
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td>Man Power</td>
                                    <td>Manager HR</td>
                                </tr>



                            </tbody>


                        </table>

                    </a>


                    <a href="#" class="list-group-item list-group-item-success"><strong>3. Routing .</strong></a>
                    <a href="#" class="list-group-item">
                        <strong> 1.</strong> User will select the type of minute as per guideline given above and forward it to HOD through supervisor if any.
                        <br />
                        <strong> 2.</strong> HOD should seek technical advice from technical person as mentioned above and then forward the minute as below:


                        <table class="table table-bordered mb-none table-hover">

                            <tbody>

                                <tr>
                                    <td>1</td>
                                    <td>Medical Equipment</td>
                                    <td>Chief Consultant</td>
                                </tr>

                                <tr>
                                    <td>2</td>
                                    <td>All Other Minute Sheets </td>
                                    <td>GM Logistics</td>
                                </tr>



                            </tbody>


                        </table>

                    </a>



                    <a href="#" class="list-group-item list-group-item-success"><strong>4. Approval/Sanctioning Limits .</strong></a>
                    <a href="#" class="list-group-item">
                        <strong> 1.</strong> All minutes up to Rs.200,000/ will be approved by administrator for Rawalpindi Hospital and upto Rs,300,000/ by ED for Hospital/PIO/ACCO/Real Estate.
                        <br />
                        <strong> 2.</strong> All minutes above Rs.300,000/ will be forwarded to president through ED for approval.

                        <br />
                        <strong>3.</strong> After approval of a minute sheet it will be automatically forwarded to GM Logistics for issuance of P.O or W.O.


                    </a>

                    <a href="#" class="list-group-item active"><strong>  Facilities by System for Users</strong></a>
                    <a href="#" class="list-group-item">
                        <strong> 1.</strong> All users can check the progress of their minutes at any time and at any stage.
                        <br />
                        <strong> 2.</strong> All users are required to follow up their minutes for speedy completion / approval.


                    </a>

                </div>






            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
        </div>

    </div>
</div>