SAGERPNEW2018/Controllers/DepartmentController.cs
using HRandPayrollSystemModel.DBModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Filters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        [UserRightFilters]
        public ActionResult Index()
        {
            try
            {
                tblDepartment a = new tblDepartment();
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);
                return View(a);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [UserRightFilters]
        public ActionResult create(tblDepartment a)
        {
            try
            {
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);
                a.DepartmentCode = a.geneartedepartmentCode(Convert.ToInt32("0" + new SAGERPNEW2018.Models.SystemLogin().GetUser().ProjectIDs));


                return View(a);
            }
            catch (Exception ex)
            {

                return View(a);
            }

        }
        [UserRightFilters]
        public ActionResult delete(int id)
        {
            try
            {
                tblDepartment a = new tblDepartment();

                bool c = a.DeleteData(id);
                if (c)
                {
                    return RedirectToAction("Index");

                }
                TempData["Dependancy"] = "This Record Using In Another Table";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }


        }
        [UserRightFilters]

        public ActionResult Edit(string id)
        {
            try
            {
                string[] IDo = id.Split('|');

                tblDepartment a = new tblDepartment();
                var obj = a.getAlldataByID(Convert.ToInt32(IDo[0]));

                ViewData["Editmode"] = true;
                if (IDo[1] == "0")
                {
                    a.IsView = true;
                }
                obj.IsView = a.IsView;
               
                return View("create", obj);

            }
            catch (Exception ex)
            {
                return View("create");
            }

        }

        [UserRightFilters]

        public ActionResult Save(tblDepartment model)
        {
            try
            {
                model.ProjectID = Convert.ToInt32("0"+ new SAGERPNEW2018.Models.SystemLogin().GetUser().ProjectIDs);
                if (model.SelectType != null)
                {
                    model.AllowTypeIDs = string.Join(",", model.SelectType);
                }

                int check;

                if (model.DepartmentID > 0)
                {
                    model.ModifiedDate = DateTime.Now;
                   
                    model.ModifiedID = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid;

                    model.ModifiedIP = new SAGERPNEW2018.Models.SystemLogin().GetUser().IP;
                    check = check = model.UpdateData(model);
                }
                else
                {
                    model.DepartmentCode = model.geneartedepartmentCode(Convert.ToInt32("0" + new SAGERPNEW2018.Models.SystemLogin().GetUser().ProjectIDs));
                    model.EntryDate = DateTime.Now;
                    model.EntryID = new SAGERPNEW2018.Models.SystemLogin().GetUser().Userid;
                    model.EntryIP = new SAGERPNEW2018.Models.SystemLogin().GetUser().IP;
                    check = model.addata(model);
                }

                if (check > 0)
                {
                    return RedirectToAction("Index");

                }
                return RedirectToAction("create", model);

            }
            catch (Exception ex)
            {

                return View("create");
            }
        }

        public ActionResult Duplicate(string Name, string ID)
        {
            try
            {
                string json = "";
                var list = new tblDepartment().checkDuplicate(Convert.ToInt32(ID), Name, Convert.ToInt32("0" + new SAGERPNEW2018.Models.SystemLogin().GetUser().ProjectIDs));
                if (list.Count() > 0)
                {
                    json = " Duplicate Record Found ";
                }
                return Json(JsonConvert.SerializeObject(json), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {


                return Json(JsonConvert.SerializeObject("Error"), JsonRequestBehavior.AllowGet);

            }


        }
    }
}

SAGERPNEW2018/Views/Department/Index.cshtml
@model HRandPayrollSystemModel.DBModel.tblDepartment

@{
    ViewBag.Title = "Department Information";
}


<div id="modals"></div>

<header class="page-header">
    <h2>@ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="~/home/index">

                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Setup</span></li>
            <li><span>@ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All @ViewBag.Title Data</h2>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-none table-hover" id="UserTable">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Department </th>
                    <th>Ordering no </th>
                    <th>Inactive </th>

                    <th width="100px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @foreach (var item in Model.getAllDepartmentdata(Convert.ToInt32("0"+ new SAGERPNEW2018.Models.SystemLogin().GetUser().ProjectIDs)))
                {
                    <tr>
                        <td> @item.DepartmentCode </td>
                        <td> @item.DepartmentName </td>
                        <td> @item.OrderNo </td>
                        <td> @item.Inactive </td>


                        <td>
                            @if (Convert.ToBoolean(Model.Isedit))
                            {

                                <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.DepartmentID)">
                                    <i class="fa fa-pencil"></i>

                                </a>
                            }
                            @*@if (Convert.ToBoolean(Model.Isdelete))
                                {
                                    <a href="#basic" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Delete" onclick="Del(@item.ProjectID)">
                                        <i class="glyphicon glyphicon-trash"></i>

                                    </a>
                                }*@
                            <a href="#" class="on-default edit-row" title="View" onclick="view(@item.DepartmentID)">
                                <i class="fa fa-table"></i>

                            </a>
                            @*<button class="btn btn-success btn-xs" onclick="view(@item["Voucherid"])"><span class="glyphicon glyphicon-blackboard"></span> View</button>*@
                        </td>

                    </tr>
                }
            </tbody>

        </table>
    </div>

</section>


<script>

    $(document).ready(function () {
        //$('#btnTriggerEdit').click();
        $("#modals").load('/CustomClasses/IndexModaling.html')


            $("#UserTable").dataTable(
               {
                   "aoColumns": [{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true },
                       { "bSearchable": false }],
                   "bSort": true,

                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',
                                  title: 'Department Information',
                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: 'Company Information',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: 'Company Information',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: 'Company Information',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: 'Company Information',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
            var a = '@TempData["Dependancy"]'
            if (a != "") {
                $("#basicDendent").modal('show');
            }
        })

        function add() {
            window.location.href = "/Department/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/Department/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/Department/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/Department/Edit/" + id + "|0"

        }

</script>







SAGERPNEW2018/Views/Department/create.cshtml
@model HRandPayrollSystemModel.DBModel.tblDepartment

@{
    ViewBag.Title = "Department Information ";
}


@using (@Html.BeginForm("Save", "Department", FormMethod.Post, new { @id = "myform", enctype = "multipart/form-data" }))
{
    if (Model.DepartmentID  > 0)
    {
        if (Model.IsView)
        {
            ViewBag.Title = "Department Info View";
        }
        else
        {
            ViewBag.Title = "Department Info Edit";
        }

    }
    else
    {

        ViewBag.Title = " Department Info Create";

    }

    <header class="page-header">
        <h2>@ViewBag.Title</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="~/home/index">

                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Setup</span></li>
                <li><span>Department Info</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">Department Info</h2>
                        <p class="panel-subtitle">
                            Form control for input Department data .
                        </p>
                    </header>
                    <div class="panel-body">



                        @Html.HiddenFor(model => model.DepartmentID)
                        @*<div class="form-group">
                            <label class="col-sm-2 control-label">Project <span class="required">*</span></label>
                            <div class="col-sm-9 ">

                                @Html.DropDownListFor(model => model.ProjectID, Model.LoadProjects(), "Select Project", new { @class = "form-control selectpicker", required = "required" })

                            </div>
                        </div>*@
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Department Title <span class="required">*</span></label>
                            <div class="col-sm-8 ">
                                @Html.TextBoxFor(model => model.DepartmentName, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Title" })

                            </div>
                        </div>
                        


                        <div class="form-group">
                            <label class="col-sm-2 control-label">Department Code<span class="required">*</span></label>
                            <div class="col-sm-3 ">
                              
                                @Html.TextBoxFor(model => model.DepartmentCode, new {  @readonly= "readonly", @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Department Code" })

                            </div>
                            <label class="col-sm-2 control-label">Order No<span class="required">*</span></label>
                            <div class="col-sm-3 ">
                                @Html.TextBoxFor(model => model.OrderNo, new { @class = "form-control uneditable-input ", type = "Number", required = "required", @placeholder = "Enter Order NO" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label"> Allow Type  <span class="required">*</span></label>
                            <div class="col-sm-8 ">
                           

                                <select class="selectpicker form-control" id="SelectType" name="SelectType" multiple>
                                    @{
                                        var Typlist = new HRandPayrollSystemModel.DBModel.tblEminuteSubType().loadMinutetype();
                                        foreach (var item in Typlist)
                                        {
                                            <option value="@item.Value"> @item.Text </option>
                                        }

                                    }
                                </select>

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">InActive<span class="required"></span></label>
                            <div class="col-sm-9 ">
                                @Html.CheckBoxFor(model => model.Inactive)
                                @*<input id="Inactive" name="Inactive" type="checkbox" value="@Model.Inactive" />*@

                            </div>
                        </div>





                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="button" id="cancelll" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}





<script>




    function postform() {
        debugger;
        var ReturnValue = true

        $("#myform").validate();



        var Data = { Name: $('#DepartmentName').val(), ID: $("#DepartmentID").val() }
        $.ajax({
            async: false,
            url: "/Department/Duplicate",
            data: Data,
            success: function (data) {

                var c =JSON.parse(data);
                if (c!="") {
                    bootbox.alert(c)
                    ReturnValue = false;
                }
            },
            error: function () {
                ReturnValue = false;
                bootbox.alert("Error")
            }
        })
        if (ReturnValue) {
            $("#myform").submit();

        }

    }
    $(document).ready(function () {
       // $('#Myform :input').select()

        $('.selectpicker').selectpicker();


        if ('@ViewData["Editmode"]' == 'True') {



            $('#SelectType').selectpicker('val', [@Model.AllowTypeIDs]);


        }

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }

    });


</script>


